[build]
  command = "npm run build"
  publish = "build"


[[redirects]]
  from = "/api"
  to = "https://min-simple-blog.herokuapp.com/api"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}